# Ejecutar desde reproducibilidad: Rscript scripts/R/diagnostico.R
# Diagnostica las entradas y reproduce los filtros de tesis_anthony.R.
# No modifica ni corrige datos originales.
suppressPackageStartupMessages({library(haven); library(dplyr); library(tidyr)})
salida <- 'output/diagnostico'
dir.create(salida, recursive = TRUE, showWarnings = FALSE)
guardar <- function(x, nombre) write.csv(x, file.path(salida, paste0(nombre, '.csv')), row.names = FALSE, na = '')
mart <- read_dta('data/raw/Estimations.dta')
elec <- read_dta('data/raw/elections_dataset.dta')
resumen <- function(d, nombre, pais) data.frame(base = nombre, filas = nrow(d), columnas = ncol(d), paises = n_distinct(d[[pais]]), desde = min(d$year, na.rm=TRUE), hasta = max(d$year, na.rm=TRUE))
guardar(bind_rows(resumen(mart, 'Martinez', 'countrycode'), resumen(elec, 'Girardi', 'iso3code')), 'bases')
faltantes <- function(d, vars, nombre) data.frame(base=nombre, variable=vars, faltantes=sapply(d[vars], function(x) sum(is.na(x))), total=nrow(d))
vm <- c('countrycode','year','lngdp14','lndn13','fiw','fiw2')
ve <- c('key','iso3code','year','parliamentary','left_gov','left_win','pres_leftmargin','parl_leftmargin','exclude')
guardar(bind_rows(faltantes(mart, vm, 'Martinez completa'), faltantes(elec, ve, 'Girardi completa'), faltantes(filter(mart, between(year,1992,2013)),vm,'Martinez 1992-2013'), faltantes(filter(elec,between(year,1992,2013)),ve,'Girardi 1992-2013')), 'faltantes')
duplicados_m <- mart |> count(countrycode,year) |> filter(n>1)
duplicados_e <- elec |> count(key) |> filter(n>1)
guardar(duplicados_m, 'duplicados_pais_anio_martinez')
guardar(duplicados_e, 'duplicados_key_girardi')
guardar(elec |> count(exclude, .drop=FALSE), 'codigos_exclusion')
panel <- mart |> filter(between(year,1992,2013)) |> select(all_of(vm)) |> filter(!is.na(lngdp14), !is.na(lndn13), !is.na(fiw))
e0 <- elec |> rename(countrycode=iso3code)
e1 <- e0 |> filter(exclude != 1)
e2 <- e1 |> filter(between(year,1992,2013))
e3 <- e2 |> mutate(treatment=if_else(parliamentary==0,left_win,left_gov), margin_victory=if_else(parliamentary==0,pres_leftmargin,parl_leftmargin), election_year=year) |> filter(!is.na(treatment),!is.na(margin_victory))
guardar(data.frame(etapa=c('Martinez original','Martinez 1992-2013','Martinez sin faltantes PIB/NTL/FiW','Girardi original','Girardi exclude != 1 (R elimina NA)','Girardi 1992-2013','Girardi tratamiento y margen disponibles'), n=c(nrow(mart),sum(between(mart$year,1992,2013)),nrow(panel),nrow(e0),nrow(e1),nrow(e2),nrow(e3))), 'flujo_muestra')
guardar(e3 |> add_count(countrycode,election_year,name='n_elecciones') |> filter(n_elecciones>1) |> select(key,countrycode,election_year,parliamentary,election_date,treatment,margin_victory,n_elecciones), 'elecciones_mismo_pais_anio')
stopifnot(nrow(duplicados_m)==0)
cobertura <- e3 |> select(key,countrycode,election_year,parliamentary,treatment,margin_victory) |> uncount(4,.id='k') |> mutate(year=election_year+k) |> left_join(panel |> transmute(countrycode,year,disponible=TRUE),by=c('countrycode','year'))
por_eleccion <- cobertura |> group_by(key,countrycode,election_year,parliamentary) |> summarise(anios_disponibles=sum(!is.na(disponible)), anios_presentes=paste(year[!is.na(disponible)],collapse=';'), anios_faltantes=paste(year[is.na(disponible)],collapse=';'), .groups='drop')
guardar(por_eleccion,'cobertura_por_eleccion')
guardar(por_eleccion |> count(anios_disponibles),'distribucion_cobertura_elecciones')
por_grupo <- cobertura |> group_by(countrycode,election_year) |> summarise(n_elecciones=n_distinct(key), anios_disponibles=n_distinct(year[!is.na(disponible)]), treatment=mean(treatment), margin_victory=mean(margin_victory), .groups='drop')
guardar(por_grupo,'cobertura_muestra_agrupada')
guardar(por_grupo |> filter(anios_disponibles>0) |> count(anios_disponibles), 'distribucion_cobertura_muestra_final')
guardar(panel |> count(countrycode,name='anios_panel'), 'cobertura_panel')
guardar(e3 |> anti_join(panel |> distinct(countrycode),by='countrycode') |> distinct(countrycode), 'paises_electorales_sin_panel')
guardar(data.frame(control=c('Duplicados pais-anio Martinez','Duplicados key Girardi','Filas identicas completas Martinez','Filas identicas completas Girardi','FiW2 distinto de FiW al cuadrado en panel','Tratamiento fuera de 0/1 en elecciones elegibles','Grupos pais-anio con mas de una eleccion','Filas con exclude faltante en 1992-2013'), n=c(nrow(duplicados_m),nrow(duplicados_e),sum(duplicated(mart)),sum(duplicated(elec)),sum(abs(panel$fiw2-panel$fiw^2)>1e-8,na.rm=TRUE),sum(!e3$treatment %in% c(0,1)),sum(por_grupo$n_elecciones>1),sum(is.na(elec$exclude)&between(elec$year,1992,2013)))), 'controles')
capture.output(sessionInfo(),file=file.path(salida,'sessionInfo.txt'))
print(read.csv(file.path(salida,'flujo_muestra.csv')))
print(read.csv(file.path(salida,'distribucion_cobertura_muestra_final.csv')))
print(read.csv(file.path(salida,'controles.csv')))
